<footer id="ef-footer">
      <ul class="ef-social-bar list-inline">
        <li><a class="icn-twitter-squared" href="#"></a></li>
        <li><a class="icn-facebook-squared" href="#"></a></li>
        <li><a class="icn-instagram" href="#"></a></li>
        <li><a class="icn-behance" href="#"></a></li>
        <li><a class="icn-linkedin-squared" href="#"></a></li>

        <!-- Uncomment icon you need -->

        <!-- <li><a class="icn-stumbleupon" href="#"></a></li> -->
        <!-- <li><a class="icn-skype" href="#"></a></li> -->
        <!-- <li><a class="icn-youtube-play" href="#"></a></li> -->
        <!-- <li><a class="icn-soundcloud" href="#"></a></li> -->
        <!-- <li><a class="icn-tumblr-squared" href="#"></a></li> -->
        <!-- <li><a class="icn-gplus-squared" href="#"></a></li> -->
        <!-- <li><a class="icn-pinterest-squared" href="#"></a></li> -->
        <!-- <li><a class="icn-vimeo-squared" href="#"></a></li> -->
        <!-- <li><a class="icn-vkontakte" href="#"></a></li> -->
        <!-- <li><a class="icn-picasa" href="#"></a></li> -->
        <!-- <li><a class="icn-lastfm" href="#"></a></li> -->
      </ul>
      <div id="ef-copyrights">
        &copy; 2005 - <?php echo date('Y') ?> by <a href="http://www.turista.com.mx">Turista.com.mx</a> S.A. de C.V.
         Photos Powered by <a href="http://flickr.com"><span style="color: rgb(0, 102, 204);">Flick</span><span style="color: rgb(255, 0, 153);">r</span></a>
      </div>
    </footer>
