    <section id="ef-header">

      <a href="/" id="ef-logo"><img src="/assets/logo.png" alt="Puebla Pictures"></a>
      
      

      <nav class="top-bar">
        
        <ul class="title-area">
          <li class="toggle-topbar menu-icon"><a href="#"><span>Menu</span></a></li>
        </ul>

        <section class="top-bar-section">
          <!-- Nav Section -->
          
        <?php echo $this->navigation('navigation')->menu()->setPartial('layout/partial/nav-top-bar');?>


        </section>
      </nav>
    </section>
    
    <div id="ef-slider-overlay"><img src="/assets/slider-overlay.png" alt=""></div>
    
    
