<!DOCTYPE html>
<html lang="en" class="no-js">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="shortcut icon" href="assets/favicon.png">

    <title>Gallery - Fidelity</title>

    <link href='http://fonts.googleapis.com/css?family=Magra:400,700|Open+Sans:400,300,300italic,400italic,600,700,600italic,700italic,800,800italic&amp;subset=latin,latin-ext,greek-ext,greek,vietnamese,cyrillic' rel='stylesheet' type='text/css'>

    <link href="css/bootstrap.min.css" rel="stylesheet">
    <link href="css/topbar.min.css" rel="stylesheet">
    <link href="css/shortcodes.css" rel="stylesheet">
    <link href="inc/fontello/css/fontello.css" rel="stylesheet">
    <link href="inc/fontello/css/animation.css" rel="stylesheet">
    <link href="css/shadowbox/shadowbox.css" rel="stylesheet">
    <link href="css/style.css" rel="stylesheet">
    <link href="css/colors.css" rel="stylesheet">

    <script type="text/javascript" src="js/modernizr.custom.js"></script>
    <script type="text/javascript" data-pace-options='{ "eventLag": false }' src="js/pace.min.js"></script>

    <!--[if lt IE 9]>
      <link href="css/ie.css" rel="stylesheet">
      <script src="js/ie/html5shiv.js"></script>
      <script src="js/ie/respond.min.js"></script>
    <![endif]-->
  </head>
  
  <body class="ef-fullwidth-page ef-gallery ef-has-widgets">
  <?php echo $this->partial('partial/top-bar')?>
      <section id="ef-page-header">
      <div id="ef-head-inner">
        <div id="ef-page-title"><span>Gallery</span></div>
        <div id="ef-page-controls">
          <a id="ef-widgets-tab" class="icn-ef" href="#"></a>
        </div>
      </div>
      <aside id="ef-widgets">
        <div id="ef-widgets-pane">
          <div id="ef-widgets-inner">

            <section class="ef-widget">
              <div class="widget_text widget">
                <h6>About Me</h6>
              
                <p>Mauris molestie mauris et suscipit sollicitudin. Donec sit amet elit sit amet magna interdum consequat. Vestibulum dignissim gravida risus, vitae blandit velit tincidunt a. Vivamus consequat diam eleifend purus luctus congue.</p>
              </div>
            </section>

            <section class="ef-widget">
              <div class="widget widget_tag_cloud">
                <h6>Portfolio tags</h6>
              
                <div class="tagcloud">
                  <ul class="wp-tag-cloud">
                    <li><a class="tag-link" title="1 topic" href="#">man</a></li>
                    <li><a class="tag-link" title="2 topics" href="#">street</a></li>
                    <li><a class="tag-link" title="1 topics" href="#">wall</a></li>
                    <li><a class="tag-link" title="2 topics" href="#">sky</a></li>
                    <li><a class="tag-link" title="3 topics" href="#">development</a></li>
                    <li><a class="tag-link" title="1 topics" href="#">fashion</a></li>
                    <li><a class="tag-link" title="2 topics" href="#">love</a></li>
                    <li><a class="tag-link" title="4 topics" href="#">dark</a></li>
                    <li><a class="tag-link" title="2 topics" href="#">bridge</a></li>
                    <li><a class="tag-link" title="3 topics" href="#">cooking</a></li>
                    <li><a class="tag-link" title="4 topics" href="#">light</a></li>
                    <li><a class="tag-link" title="1 topics" href="#">night</a></li>
                    <li><a class="tag-link" title="1 topics" href="#">night</a></li>
                    <li><a class="tag-link" title="2 topics" href="#">website</a></li>
                    <li><a class="tag-link" title="1 topics" href="#">road</a></li>
                    <li><a class="tag-link" title="5 topics" href="#">party</a></li>
                  </ul>
                </div>

              </div>
            </section>

            <section class="ef-widget">
              <div class="widget widget_flickr">
                <h6>Ultimas Fotos del Turista en Flickr</h6>
              
                <ul class="jflickr clearfix"></ul>

              </div>
            </section>

            <section class="ef-widget">
              <div class="widget widget_indtagram">
                <h6>From Instagram</h6>
              
                <ul class="instagram clearfix"></ul>

              </div>
            </section>

          </div>
        </div>
      </aside>
    </section>
    
    <!-- Aca va el contenido -->
    <?php echo $this->content?>
    
    <?php echo $this->partial('partial/footer')?>
    

    <script type="text/javascript" src="js/jquery.min.js"></script>
    <script type="text/javascript" src="js/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="js/jquery.easing.min.js"></script>
    <script type="text/javascript" src="js/jquery-ui-1.10.3.custom.min.js"></script>
    <script type="text/javascript" src="js/detectmobilebrowser.min.js"></script>
    <script type="text/javascript" src="js/jquery.transit.min.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <script type="text/javascript" src="js/foundation.min.js"></script>
    <script type="text/javascript" src="js/topbar.min.js"></script>
    <script type="text/javascript" src="js/jquery.isotope.min.js"></script>
    <script type="text/javascript" src="js/imagesloaded.min.js"></script>
    <script type="text/javascript" src="js/video/video.min.js"></script>
    <script type="text/javascript" src="js/video/bigvideo.min.js"></script>
    <script type="text/javascript" src="js/jquery.infinitescroll.min.js"></script>
    <script type="text/javascript" src="js/jquery.nicescroll.min.js"></script>
    <script type="text/javascript" src="js/shortcodes/inview.min.js"></script>
    <script type="text/javascript" src="js/jquery.flexslider.min.js"></script>
    <script type="text/javascript" src="js/shadowbox/shadowbox.js"></script>

    <script type="text/javascript" src="js/jflickrfeed.min.js"></script>
    <script type="text/javascript" src="js/instagram.min.js"></script>

    <script type="text/javascript" src="js/shortcodes/custom.js"></script>
    <script type="text/javascript" src="js/setup.js"></script>
    <script type="text/javascript" src="js/app.js"></script>
  
  
  </body>
  
  </html>
