<?php echo $this->doctype();
$this->headMeta()->appendHttpEquiv('Content-Type',
    'text/html; charset=UTF-8')
    ->appendHttpEquiv('Content-Language', 'es-MX')
    ->appendName('viewport', 'width=device-width, initial-scale=1.0, maximum-scale=1.0')
    ->appendName('author','www.turista.com.mx');

if (!isset($this->bodyClass)) {
    $this->bodyClass = 'fireform-slider page-template-templateshome-template ef-overlay';
}

if (isset($this->menuCollections)){
    $menu = array($this->menuCollections);
    $page = $this->navigation('navigation');
    $page->addPages($menu);
}


$gruposnav = $this->navigation('grupos-navigation')->toArray();
$page = $this->navigation('navigation')->findOneBy('label', 'Grupos');
if ($gruposnav) {
    $page->addPages($gruposnav);
}

$page = $this->navigation('navigation')->findOneBy('id','external_sites');
$externalSites = $this->externalSites;
if ($externalSites) {
    $page->addPages($this->externalSites);
}

?>

<html lang="en">
    <head>
        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>
        <?php echo $this->headTitle($this->siteName)->setSeparator(' - ')->setAutoEscape(false) ?>

        

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/assets/favicon.png'))
                        ->appendStylesheet('http://fonts.googleapis.com/css?family=Magra:400,700|Open+Sans:400,300,300italic,400italic,600,700,600italic,700italic,800,800italic&amp;subset=latin,latin-ext,greek-ext,greek,vietnamese,cyrillic')
                        ->appendStylesheet($this->basePath() . '/css/bootstrap.min.css')
                        ->appendStylesheet($this->basePath() . '/css/topbar.min.css')
                        ->appendStylesheet($this->basePath() . '/css/shortcodes.css') 
                        
                        ->appendStylesheet($this->basePath() . '/inc/fontello/css/fontello.css')
                        ->appendStylesheet($this->basePath() . '/inc/fontello/css/animation.css')
                        ->appendStylesheet($this->basePath() . '/css/shadowbox/shadowbox.css')
                        ->appendStylesheet($this->basePath() . '/css/style.css')
                        ->appendStylesheet($this->basePath() . '/css/colors.css')
        ?>

        <!-- Scripts -->
        <?php // echo $this->headScript()
//             ->prependFile($this->basePath() . '/js/bootstrap.min.js')
//             ->prependFile($this->basePath() . '/js/jquery.min.js')
//             ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
//             ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
//         ; ?>
    <script type="text/javascript" src="/js/modernizr.custom.js"></script>
    <script type="text/javascript" data-pace-options='{ "eventLag": false }' src="/js/pace.min.js"></script>

    <!--[if lt IE 9]>
      <link href="css/ie.css" rel="stylesheet">
      <script src="js/ie/html5shiv.js"></script>
      <script src="js/ie/respond.min.js"></script>
    <![endif]-->
    </head>
    <body class="<?php echo $this->bodyClass?>">
<!--     <body class="fireform-slider page-template-templateshome-template ef-fullwidth-page ef-overlay"> -->
<!--     <body class="page-template-templatesportfolio-template ef-fullwidth-page ef-has-widgets"> -->
    <?php echo $this->partial('layout/partial/top-bar')?>   
    
      
            <?php echo $this->content; ?>
      
        <?php echo $this->partial('layout/partial/footer')?>

        <?php echo $this->inlineScript() ?>
    </body>
</html>

   <script type="text/javascript" src="/js/jquery.min.js"></script>
    <script type="text/javascript" src="/js/jquery-migrate-1.2.1.min.js"></script>
    <script type="text/javascript" src="/js/jquery.easing.min.js"></script>
    <script type="text/javascript" src="/js/jquery-ui-1.10.3.custom.min.js"></script>
    <script type="text/javascript" src="/js/detectmobilebrowser.min.js"></script>
    <script type="text/javascript" src="/js/jquery.transit.min.js"></script>
    <script type="text/javascript" src="/js/bootstrap.min.js"></script>
    <script type="text/javascript" src="/js/foundation.min.js"></script>
    <script type="text/javascript" src="/js/topbar.min.js"></script>
    <script type="text/javascript" src="/js/jquery.isotope.min.js"></script>
    <script type="text/javascript" src="/js/imagesloaded.min.js"></script>
    <script type="text/javascript" src="/js/video/video.min.js"></script>
    <script type="text/javascript" src="/js/video/bigvideo.min.js"></script>
    <script type="text/javascript" src="/js/jquery.infinitescroll.min.js"></script>
    <script type="text/javascript" src="/js/jquery.nicescroll.min.js"></script>
    <script type="text/javascript" src="/js/shortcodes/inview.min.js"></script>
    <script type="text/javascript" src="/js/jquery.flexslider.min.js"></script>
    <script type="text/javascript" src="/js/shadowbox/shadowbox.js"></script>

    <script type="text/javascript" src="/js/jquery.mobilemenu.min.js"></script>
    <script type="text/javascript" src="/js/jflickrfeed.min.js"></script>
    <script type="text/javascript" src="/js/instagram.min.js"></script>

    <script type="text/javascript" src="/js/shortcodes/custom.js"></script>
    <script type="text/javascript" src="/js/setup.js"></script>
    <script type="text/javascript" src="/js/app.js"></script>
